- name: Реализация автоматической доставки новых коммитов на тестовый сервер
  hosts: test_server
  tasks:
    - name: Задача 1 - Реализовать бэкенд базы данных
      postgresql_db:
        name: mydatabase
        state: present

    - name: Задача 2 - Реализовать доставку обновлений на dev сервер
      git:
        repo: https://github.com/myproject.git
        dest: /path/to/dev_server
        version: master
        update: yes
      notify: send_notification

    - name: Задача 3 - Реализовать уведомления в Telegram
      block:
        - name: Уведомление об успешной заливке
          debug:
            msg: |
              Проект: [название проекта]
              Дата: [дата и время]
              Ветка: [название ветки]
              Коммит: [номер коммита], [комментарий коммита]
              Комментарий: Успешно доставлен.

        - name: Уведомление об неуспешной заливке
          debug:
            msg: |
              Проект: [название проекта]
              Дата: [дата и время]
              Ветка: [название ветки]
              Коммит: [номер коммита], [комментарий коммита]
              Комментарий: Ошибка создания бэкапа БД / Ошибка при слиянии (merge), [лог ошибки]

  handlers:
    - name: send_notification
      # Отправка уведомления в Telegram
      # Реализуйте здесь код для отправки уведомления в Telegram
      # Можете использовать, например, Telegram API или библиотеки, поддерживающие отправку сообщений в Telegram.
